"""add batch_event_correlations

Revision ID: 17036fa93990
Revises: 8129dd6ca93c
Create Date: 2026-09-17 16:40:34.311517
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '17036fa93990'
down_revision: str | None = '8129dd6ca93c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_event_correlations',
    sa.Column('event_type_a', sa.String(length=128), nullable=False),
    sa.Column('event_type_b', sa.String(length=128), nullable=False),
    sa.Column('bucket_minutes', sa.BigInteger(), nullable=False),
    sa.Column('n_buckets', sa.BigInteger(), nullable=False),
    sa.Column('mean_count_a', sa.Float(), nullable=False),
    sa.Column('mean_count_b', sa.Float(), nullable=False),
    sa.Column('pearson_r', sa.Float(), nullable=True),
    sa.Column('covariance', sa.Float(), nullable=True),
    sa.Column('window_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_a', 'event_type_b', 'bucket_minutes', name='uq_batch_correlation_pair')
    )
    op.create_index('ix_batch_correlation_pearson', 'batch_event_correlations', ['pearson_r'], unique=False)
    op.create_index(op.f('ix_batch_event_correlations_created_at'), 'batch_event_correlations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_event_correlations_created_at'), table_name='batch_event_correlations')
    op.drop_index('ix_batch_correlation_pearson', table_name='batch_event_correlations')
    op.drop_table('batch_event_correlations')
    # ### end Alembic commands ###
