"""add batch_event_rollups

Revision ID: 8129dd6ca93c
Revises: 0001_initial_schema
Create Date: 2026-09-17 14:54:17.907764
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8129dd6ca93c'
down_revision: str | None = '0001_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_event_rollups',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('distinct_correlation_ids', sa.BigInteger(), nullable=False),
    sa.Column('distinct_users', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('avg_amount', sa.Float(), nullable=False),
    sa.Column('late_event_count', sa.BigInteger(), nullable=False),
    sa.Column('replay_event_count', sa.BigInteger(), nullable=False),
    sa.Column('window_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'region', 'hour_bucket', name='uq_batch_rollup_bucket')
    )
    op.create_index(op.f('ix_batch_event_rollups_created_at'), 'batch_event_rollups', ['created_at'], unique=False)
    op.create_index('ix_batch_rollup_hour', 'batch_event_rollups', ['hour_bucket'], unique=False)
    op.create_index('ix_batch_rollup_type_hour', 'batch_event_rollups', ['event_type', 'hour_bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batch_rollup_type_hour', table_name='batch_event_rollups')
    op.drop_index('ix_batch_rollup_hour', table_name='batch_event_rollups')
    op.drop_index(op.f('ix_batch_event_rollups_created_at'), table_name='batch_event_rollups')
    op.drop_table('batch_event_rollups')
    # ### end Alembic commands ###
